parameters:
#    celmedia_site.example.class: Celmedia\SiteBundle\Example

services:
#    celmedia_site.example:
#        class: %celmedia_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
